### ISSUE TITLE
time-managment.rb possibly not included in gem

### ISSUE THREAD

**Issue by JPain** [pliyosenpai/sensu-plugins-influxdb-metrics-checker#10]
Ello! We got his error on 0.6.0
```
/opt/sensu/embedded/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- ./time-management (LoadError)
from /opt/sensu/embedded/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-plugins-influxdb-metrics-checker-0.6.0/bin/check-influxdb-metrics.rb:12:in `<top (required)>'
from /opt/sensu/embedded/bin/check-influxdb-metrics.rb:22:in `load'
from /opt/sensu/embedded/bin/check-influxdb-metrics.rb:22:in `<main>'
```

I think you missed `time-managment.rb` when packing for the gem, but I can't easily figure it out in the gemspec.
I'll do some reading and have a stab at it in a few days if you don't.

Fantastic repo you have, by the way! Your readme kicks ass!

**Comment by adrianlski** [comment]
Juanjo came to the office and we did this:
https://github.com/pliyosenpai/sensu-plugins-influxdb-metrics-checker/pull/11

**Comment by pliyo** [comment]
Hey @JPain sorry it took me so long to reply, version **0.6.1** is up and running, including the changes in the PR that Adrian left up there. That should fix the issue.

If in the worst case scenario it didn't, please use 0.5.0 instead that we know that what's working. 

Thanks a lot for reaching me out, I really appreciate the feedback. Let's keep the issue open until we know for sure that 0.6.1 will work. I'll keep an eye on this.

Cheers!

**Comment by pliyo** [comment]
Closing the issue since I got confirmation just now that is working :grin:
