### ISSUE TITLE
truncating decimals

### ISSUE THREAD

**Issue by andyroyle** [pliyosenpai/sensu-plugins-influxdb-metrics-checker#2]
Decimals are being printed out in their default form at the moment complete with 18 places of precision `0.45200950511416466%`

Probably worthwhile to truncate to, say 5 decimal places just to make it easier to read

**Comment by pliyo** [comment]
Hey @andyroyle thanks for posting this. 
This issue has been addressed here: https://github.com/pliyosenpai/sensu-plugins-influxdb-metrics-checker/pull/3
